### ISSUE TITLE
Input doesn't autofocus

### ISSUE THREAD

**Issue by Josasp** [pedelman/brackets-surround#9] opened 2014-08-14 12:49 UTC
Input doesn't autofocus.

Running Brackets 0.42.0-13957 and fix to extension from rarebush

**Comment by jkillian** [comment] 2014-08-19 15:35
+1
I'm encountering this issue as well. I don't know anything about the Brackets API, but I'm happy to submit a pull request if anyone can guide me in the right direction for the fix

**Comment by invokablegmbh** [comment] 2014-09-05 07:23
Just add 
`$('#surround_input').focus();`
as a last line to the surround-function:

```
 function surround() {
        var _t = _getSelectedText(),
            _output = "";
        Dialogs.showModalDialogUsingTemplate(surroundHtml);
        $('#surround_input').keyup(function (e) {
            if (e.which === 13) {
                e.preventDefault();
                var _c = $('#surround_input').val();

                if (_c === null) {
                    return;
                }
                if (cases[_c] !== undefined) {
                    _output = _c + _t + cases[_c];
                } else {
                    if (_isHTML(_c)) {
                        if (_closeHTML(_c) === false) {
                            Dialogs.cancelModalDialogIfOpen('surround_input');
                            return;
                        }
                        _output = _c + _t + _closeHTML(_c);
                    } else {
                        _output = _c + _t + _c;
                    }
                }
                $('.surround_input').fadeOut(300);
                Dialogs.cancelModalDialogIfOpen('surround_input');
                _replaceActiveSelection(_output);
            }
        });
        $('#surround_input').focus();
    }
```

**Comment by jkillian** [comment] 2014-09-17 01:37
Thanks jarmediagmbh. Just wanted to point out that [this pull request](https://github.com/pedelman/brackets-surround/pull/10) will fix the issue if merged.

**Comment by pedelman** [comment] 2014-09-19 16:37
This has been resolved, thanks for the feedback. If you had it previously installed through the extensions registry, you can now update and it should work as intended.

**Closed as completed by pedelman** 2014-09-19 16:37 UTC
